### ISSUE TITLE
Problema no atualizar questão

### ISSUE THREAD

**Issue by lsoaresesilva** [lsoaresesilva/letscode#101]
Ao clicar em atualizar questão que é carregada a questão:

- [x] Os assuntos que foram selecionados no cadastro, não aparecem na atualização pré-selecionados
- [x] O teste case apresenta apenas a saída, mas não as entradas.

**Comment by Wanessaa** [comment]
@lsoaresesilva , não conseguir fazer com que na atualização os assuntos ficassem pré-selecionados.
