### ISSUE TITLE
Criar um componente de visualização de questão

### ISSUE THREAD

**Issue by lsoaresesilva** [lsoaresesilva/letscode#102]
Critérios de aceitação:

- [x] Deve apresentar as informações da questão
- [x] Deve ter uma lista com as submissões dos estudantes. Utilizar uma tabela com nome do estudante e um botão ao lado para visualizar a submissão
- [x] Deve ter um botão: Responder. Ao ser clicado irá para a tela de edição da questão

**Comment by lsoaresesilva** [comment]
O que falta para encerrar essa Issue?

**Comment by Wanessaa** [comment]
Quando chamo a submissão dos estudantes que é um componente não aparece nada. Criei uma issue #161 descrevendo melhor.
