### ISSUE TITLE
Questões que o estudante já fez

### ISSUE THREAD

**Issue by beatrijz** [lsoaresesilva/letscode#132]
Criar um lugar para guardar as questões que o estudante já fez @lsoaresesilva

**Comment by lsoaresesilva** [comment]
Faz o pull do master.. para atualizar seu repositório.

Para verificar se o estudante fez uma questão você deve fazer:

```javascript



Questao.isFinalizada( objeto-de-uma-questao, usuario).subscribe(resultado=>{

// resultado será um % de quanto da questão o estunte fez.

})
```

OBS: para pegar o usuário logado você faz: Usuario.getUsuarioLogado(). Caso seja um outro estudante, é só passar um objeto usuario (e não estudante) para a função.
