### ISSUE TITLE
salvar o código que o aluno está fazendo para o pedido de ajuda

### ISSUE THREAD

**Issue by arthur007110** [lsoaresesilva/letscode#139]
é necessário salvar o código que o aluno está atualmente fazendo para fazer a solicitação de um pedido de ajuda.

**Comment by arthur007110** [comment]
@lsoaresesilva

**Comment by lsoaresesilva** [comment]
Roda esse comando: let submissao = this.prepararSubmissao()

Aí com esse objeto submissão, dentro dele tem o código, que é um objeto da classe Codigo. Dentro de Codigo você acessa o atributo algoritmo.
