### ISSUE TITLE
Erro quando altera uma questao fechada

### ISSUE THREAD

**Issue by Wanessaa** [lsoaresesilva/letscode#152]
A função validar não é reconhecida.

imagem do erro:
![image](https://user-images.githubusercontent.com/45123081/60404554-638fd300-9b80-11e9-990e-1887ed8269c8.png)

do onde vem o erro:
![image](https://user-images.githubusercontent.com/45123081/60404533-2e838080-9b80-11e9-9c73-4755e2339bc6.png)

**Comment by lsoaresesilva** [comment]
Qual usuário que você está usando para acessar? pois com o professor e lets não consigo clicar com o botão direito na listagem de questões fechadas.

**Comment by Wanessaa** [comment]
É melhor tira o ngIf  do component de listar questão.

**Comment by lsoaresesilva** [comment]
Só consigo corrigir isso quando a issue #166 for corrigida.

**Comment by lsoaresesilva** [comment]
Corrigi a issue. O problema é que agora estamos trabalhando com collections que dentro dela possuem todos os dados. Por exemplo:

Assunto possui questão e questão fechada. Questão fechada possui alternativas.

Ao carregar um assunto são carregadas as questões e as questões fechadas. Ao carregar as questões fechadas são carregadas as alternativas. Nesse processo são construídos os objetos a partir dos dados que estão no firestore. Com exceção de alternativas que estava vindo o dado bruto (da mesma forma como estava no firestore) e não como objeto. eu solucionei isso.
