### ISSUE TITLE
Pegar os nomes dos estudantes da turma 

### ISSUE THREAD

**Issue by beatrijz** [lsoaresesilva/letscode#154]
Estou com problema para percorrer o array de EstudantesTurma, pois quando coloco na função get juntamente com estudanteId, ocorre um erro no qual é dito que o id está vazio; 
![image](https://user-images.githubusercontent.com/44070111/60933032-00482400-a297-11e9-8d44-3f43fb31598b.png)
![image](https://user-images.githubusercontent.com/44070111/60933037-06d69b80-a297-11e9-8ba8-25cd465285eb.png)
 
bug referente a issue #109

**Comment by beatrijz** [comment]
@lsoaresesilva

**Comment by lsoaresesilva** [comment]
Um erro que observei é que no arquivo de rotas, para esse componente, estava:

{path:"visualizacao-turma/:turmaId",

sendo que no componente você tentava recuperar o parâmetro da rota por:

params['id']

Assim, alterei o código acima para ficar:

{params['turmaId']

**Comment by lsoaresesilva** [comment]
Outro problema é que no HTML você tenta mostrar um objeto e não o seu atributo:

<td>{{estudante}}</td>

Quando deveria ser:

<td>{{estudante.nome}}</td>
