### ISSUE TITLE
Reutlizar um componente fora do módulo

### ISSUE THREAD

**Issue by Wanessaa** [lsoaresesilva/letscode#161]
Bug referente a issue #102

O componente listar-estudantes-submissao,onde se encontra os estudantes que concluíram a questao, (módulo cscl) quando reutilizado no componete visualizar-questao (módulo juiz)  não aparece.

![image](https://user-images.githubusercontent.com/45123081/60761593-506a8080-a022-11e9-9598-9862000a55a1.png)
![image](https://user-images.githubusercontent.com/45123081/60761597-62e4ba00-a022-11e9-8fc3-ed2383a0b4ac.png)
![image](https://user-images.githubusercontent.com/45123081/60761600-6d9f4f00-a022-11e9-99dc-b69efdeaff36.png)
![image](https://user-images.githubusercontent.com/45123081/60761605-8576d300-a022-11e9-860a-353ee4f286c3.png)
![image](https://user-images.githubusercontent.com/45123081/60761629-db4b7b00-a022-11e9-8cdb-07564895cd56.png)

Embora o erro pareça está no parâmentro,não é porque não carrega nenhum componente que está fora do módulo.

**Comment by lsoaresesilva** [comment]
Como eu chego até a visualização de uma questão? para poder fazer o teste?

**Comment by Wanessaa** [comment]
Só clicar na questão. ( O código estava em pull request , mas eu dei merge para ir para a master).

**Comment by lsoaresesilva** [comment]
Certo. Mas veja, independente (não vi a solução do problema) não é preciso ver a listagem dos estudantes que responderam a questão já na hora de responder uma questão. Apenas ao clicar no botão como você fez.

**Comment by Wanessaa** [comment]
ah , então tá bom.
