### ISSUE TITLE
Bug com o id do usuário

### ISSUE THREAD

**Issue by beatrijz** [lsoaresesilva/letscode#170]
![image](https://user-images.githubusercontent.com/44070111/61185736-19ecc100-a633-11e9-8dd7-0373c2c4049b.png)
Tento pegar o id do estudante com essa função, mas ocorre esse erro:
![image](https://user-images.githubusercontent.com/44070111/61185748-3c7eda00-a633-11e9-8ff3-5330e35d4af0.png)
Mas quando eu tento como id direto;
![image](https://user-images.githubusercontent.com/44070111/61185774-74861d00-a633-11e9-80e6-45dc49981882.png)
Consigo pegar o nome dele;
![image](https://user-images.githubusercontent.com/44070111/61185783-8d8ece00-a633-11e9-9e65-bf4c01898cd7.png)
Bug referente a issue #103 @lsoaresesilva

**Comment by lsoaresesilva** [comment]
O link que redireciona para visualização de estudante está com algum problema. Perceba que no endereço após o /visualizacao-estudante/ tem um % .. isso indica que o link ou botão que está roteando para este componente está colocando um espaço ou algo do tipo. Dá uma olhada
