### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by joelhenrique2000** [lsoaresesilva/letscode#340]
Estava vendo as telas, e constatei que tem alguns inconsistências tanto na UI quanto na UX. Creio que seja pertinente criar um style guide para orientar futuros programadores a ter uma guia na composição da tipografia, cores, grid e afins para manter uma consistência no front-end.

**Comment by lsoaresesilva** [comment]
@joelhenrique2000 Seria bem pertinente, queres criar? Podes fazer via página da Wiki, não sei se tens acesso..

**Comment by joelhenrique2000** [comment]
Quero sim, estou também já organizando para terminar o curso de Angular já para pegar algumas issues mais importante para o projeto.

**Comment by joelhenrique2000** [comment]
Finalizado, o guia de estilo está na Wiki do projeto.
