### ISSUE TITLE
Criação dos guards

### ISSUE THREAD

**Issue by lsoaresesilva** [lsoaresesilva/letscode#66]
As rotas:

/main
/main/editor
/main/planejamentos
/main/planejamentos/cadastrar
/main/planejamentos/visualizar

Devem ser protegidas com um Guard que irá utilizar a classe Usuário e o método isUsuarioLogado() para verificar se há um usuário logado.

**Comment by jefferson1998** [comment]
![erroQuery](https://user-images.githubusercontent.com/38189967/56093333-c8029680-5e9d-11e9-8061-a1d8ee99e56a.png)

Professor, dei o ng serve e apareceu este erro no terminal. Só lembrando que já executei os comandos: git submodule init e git submodule update no pacote firestore.

**Comment by lsoaresesilva** [comment]
Acessa a pasta src/app/firestore e digita git submodule update

**Comment by jefferson1998** [comment]
Acessei a pasta: src/app/firebase-odm (onde se encontra o query.ts) e dei executei o comando, porém nada funcionou. Executei-lo também na pasta: src/app/model/firestore, porém, ainda se encontra o mesmo erro.

**Comment by lsoaresesilva** [comment]
Na pasta src/app/model/firestore digita:

git checkout master
git pull
